export const refs = {
  gallery: document.querySelector('.gallery'),
  gallerySection: document.querySelector('.gallery-section'),
  footerLink: document.querySelector('.footer__link'),
  footerBackDrop: document.querySelector('.footer__backdrop'),
  footerCloseBtn: document.querySelector('[data-modal-close]'),
  formEl: document.querySelector('.header-search-form'),
  paginationContainer: document.querySelector('#tui-pagination-container'),
  btnUp: document.getElementById('to-top-btn'),
  btnUpWrapper: document.querySelector('.btn-up'),
  noResultsTitle: document.querySelector('.no-result-title'),
  noResultsImg: document.querySelector('.no-result-image'),

  signInBtnEl: document.querySelector('.js-signIn-btn'),
  signOutBtnEl: document.querySelector('.js-signOut-btn'),
  userStatusEl: document.querySelector('.js-userStatus'),

  filterForm: document.querySelector('.js-filters-form'),
  filterYears: document.querySelector('.js-filter-years'),
  filterLanguage: document.querySelector('.js-filter-language'),
  filterGenres: document.querySelector('.js-filter-genres'),
  filtersSort: document.querySelector('.js-filter-sort'),
  filterShowBtn: document.querySelector('.js-filterShow-btn'),
  filterBar: document.querySelector('.header__filter-bar'),
};
